web:
  build: .
  restart: always
  ports:
    - "80:8080"
    - "465:465"
  links:
    - mongo
  environment:
    NODE_ENV: production
  command: bash -c "node server"

mongo:
  image: mongo
  ports:
    - "27018:27017"
  volumes:
    - ./mongo_data:/data/db