web:
  build: .
  restart: always
  ports:
    - "80:8080"
    - "465:465"
  links:
    - mongo
  environment:
    NODE_ENV: production
  command: bash -c "npm install --production && node server"

mongo:
  image: mongo
  ports:
    - "27018:27017"
